source 'https://github.com/xiaochuanxu/FFSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'FFAuthorKit_Example' do
  pod 'FFAuthorKit', :path => '../'

  target 'FFAuthorKit_Tests' do
    inherit! :search_paths

    pod 'AFNetworking', '~> 2.3'
    pod 'Masonry'
    pod 'FFAPIs'
    pod 'FFCategoryKit'
    pod 'YYWebImage'
    pod 'ReactiveCocoa', '~> 2.5'
    
  end
end
