source 'https://github.com/xiaochuanxu/FFSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'FFAuthorKit_Example' do
  pod 'FFAuthorKit', :path => '../'

  target 'FFAuthorKit_Tests' do
    inherit! :search_paths

    
  end
end
